name: "Docker"

# we're running this on pull requests so we can test it
on:
  pull_request:
# FIXME: we want this to create a "latest" release on changes
# to `dev`, and actual releases when we create "release" branches;
# does this do that?
# on:
#   push:
#     branches: ['dev', 'release']

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # we can run tests here, and require that they pass
    # but tests should pass on the pull request used to kick this job off,
    # unless we allow changes to `dev` or `release` branches without PRs
    # needs: npm-run-tests
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Build and Store Container Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: docker/Dockerfile
        push: true
        tags: cveawg/test
