name: "Black Box Testing"

# run this on a pull request for testing
on:
  pull_request:

# use a single job at first
jobs:
  run-functional-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Build and Run Services and Mongo
      run: |
        cp docker/.docker-env.example docker/.docker-env
        docker-compose --file docker/docker-compose.yml up --build &
    - name: Build and Run Test Container
      run: |
        cd test-http/
        cp docker/.docker-env.example docker/.docker-env
        docker-compose --file docker/docker-compose.yml up --build &
