name: "Black Box Testing"

# run this on a pull request for testing
on:
  pull_request:

# use a single job at first
jobs:
  run-functional-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Build and Run Services and Mongo Containers
      run: |
        cp docker/.docker-env.example docker/.docker-env
        docker-compose --file docker/docker-compose.yml build
        docker-compose --file docker/docker-compose.yml up &
    - name: Build Test Container
      run: |
        cd test-http/
        cp docker/.docker-env.example docker/.docker-env
        docker-compose --file docker/docker-compose.yml build
    - name: Run Test Container
      run: |
        cd test-http/
        docker-compose --file docker/docker-compose.yml up &
    - name: Sleep
      run: sleep 30
    - name: Load Data into MongoDb
      run: docker exec cveawg npm run populate:dev
    - name: Run Black Box Tests
      run: |
        cd test-http/
        docker exec demon pytest src/
